### ISSUE TITLE
The problem of fixedwingpathFollowing

### ISSUE THREAD

**Issue by ghost** [SASLabStevens/MASC-Architecture#2]
Dear author when I run fixedwingpathFollowing，it reminds me ：
Signals entering Bus Creator 'fixedWingPathFollowing/Bus Creator1' have duplicated names at input ports: 
HeadingAngle_turnoff (6, 11)
All signals in the resulting bus are being made unique by appending "(signal #)". Please update the labels of the signals such that they are all unique.
Symbol 'FixedWingStateBus' has multiple inconsistent definitions:
Caused by:
Elements=<8x1 Simulink.BusElement> in fixedWingPathFollowingData.sldd (Update others to match) 
Elements=<15x1 Simulink.BusElement> in pathFollowingData.sldd (Update others to match) 
how can i solve this problem

**Comment by robotics-dotcom** [comment]
hi sorry for replying you late. Please try to match let 8 match 15. I was lazy when developing this package. Please feel free to let me know if you have any questions during reproducing this work.

**Comment by Hero13rine** [comment]
Dear author
When i try to match let 8 match 15，there will be a lot of warning showed in the table, like:
_警告: Block
'FixedWingModel/FixedWingModel/HighFidelity/FixedWingNoWindNoNoise/FixedWingAutopilotModel/InnerLoopAutopilot/sup_sat'
outputs 'NaN' for element 1 of output port 1 at minor time step 0.08  
警告: The following warning occurred while simulating the Model block with block path fixedWingPathFollowing/FixedWingModel_ 
And the Xplane trashed when the model working
Is it because some of the parameters I modified do not match the parameters required during operation?
how to solve these problems

**Comment by robotics-dotcom** [comment]
hi, thank you for reaching out. I am so sorry for replying you late. Please feel free to email me if you have any questions. 

Please clearly read the steps about how to running the example in readme. Any ignored detail will lead to the failure of reproducing the result. Feel free to match 8 with 15 so that both will be unified with 15.
